# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2024 Dell Inc, or its subsidiaries.

---
# tasks file for get_bmc_facts

- name: Validate server authentication input provided by user
  ansible.builtin.fail:
    msg: "{{ get_bmc_facts_mandatory_msg }}"
  when:
    - (username is not defined or password is not defined) and (auth_token is not defined)

- name: Fail when more than one valid authentication method is provided
  ansible.builtin.fail:
    msg: "{{ get_bmc_facts_mutual_exclusive_msg }}"
  when:
    - ((username is defined or password is defined) and auth_token is defined)

- name: Get Firmware Inventory when username and password are defined
  when: username is defined and password is defined
  block:
    - name: Get Firmware Inventory
      community.general.redfish_info:
        category: Update
        command: GetFirmwareInventory
        baseuri: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result
      delegate_to: localhost

    - name: Extract all FW versions to facts
      ansible.builtin.set_fact:
        get_bmc_facts_all_fw_versions: "{{ get_bmc_facts_all_fw_versions | default({}) | combine({item['Id'] | lower: item['Version']}) }}"
      loop: "{{ result.redfish_facts.firmware.entries }}"

- name: Get Firmware Inventory when auth_token is defined
  when: auth_token is defined
  block:
    - name: Get Firmware Inventory
      community.general.redfish_info:
        category: Update
        command: GetFirmwareInventory
        baseuri: "{{ hostname }}"
        auth_token: "{{ auth_token }}"
      register: result
      delegate_to: localhost

    - name: Extract all FW versions to facts
      ansible.builtin.set_fact:
        get_bmc_facts_all_fw_versions: "{{ get_bmc_facts_all_fw_versions | default({}) | combine({item['Id'] | lower: item['Version']}) }}"
      loop: "{{ result.redfish_facts.firmware.entries }}"

- name: Print all Versions
  ansible.builtin.debug:
    msg: "{{ get_bmc_facts_all_fw_versions }}"
